# Application Settings
replicas: 1
persistence:
  enabled: true
  size: 10Gi
  storageClassName: hd-hostpath
headlessService: false
createConfigmap: true
autoscaling:
  enabled: false
resources: {}

# Security and Access Control Settings
rbac:
  create: true
serviceAccount:
  create: true
admin:
  existingSecret: grafana-admin-user-password # pragma: allowlist secret
  userKey: admin-user
  passwordKey: admin-password # pragma: allowlist secret
envFromSecrets:
  - name: loki-gateway-password

# Networking
service:
  type: NodePort
  nodePort: 30110
ingress:
  enabled: false

# Data Sources, Dashboards & Alerts
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
      - name: Loki
        type: loki
        url: http://loki-gateway.monitoring.svc.cluster.local
        user: meshuser
        secureJsonData:
          password: $LOKI_GATEWAY_PASSWORD

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    # Ref: https://grafana.com/grafana/dashboards/13332-kube-state-metrics-v2/
    kube-state-metrics-v2:
      gnetId: 13332
      revision: 12
      datasource: Prometheus
    # Ref: https://grafana.com/grafana/dashboards/12660-kubernetes-persistent-volumes/
    kubernetes-persistent-volumes:
      gnetId: 12660
      revision: 1
      datasource: Prometheus
    # Ref: https://grafana.com/grafana/dashboards/12006-kubernetes-apiserver/
    kubernetes-apiserver:
      gnetId: 12006
      revision: 1
      datasource: Prometheus
    # Ref: https://grafana.com/grafana/dashboards/315-kubernetes-cluster-monitoring-via-prometheus/
    kubernetes-cluster-monitoring:
      gnetId: 315
      revision: 3
      datasource: Prometheus
    # Ref: https://grafana.com/grafana/dashboards/15141-kubernetes-service-logs/?tab=revisions
    loki-kubernetes-logs:
      gnetId: 15141
      revision: 1
      datasource: Loki
dashboardsConfigMaps: {}

alerting: {}
notifiers: {}
