###############################################################################
# General
###############################################################################

replicas: 1
persistence:
  enabled: true
  size: 10Gi
headlessService: false
createConfigmap: true
autoscaling:
  enabled: false
resources: {}

###############################################################################
# Security
###############################################################################

rbac:
  create: true
serviceAccount:
  create: true
admin:
  existingSecret: grafana-admin-user-password # pragma: allowlist secret
  userKey: admin-user
  passwordKey: admin-password # pragma: allowlist secret

###############################################################################
# Networking
###############################################################################

service:
  type: NodePort
  nodePort: 30110
ingress:
  enabled: false

###############################################################################
# Data Sources, Alerts and Dashboards
###############################################################################

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    # Ref: https://grafana.com/grafana/dashboards/13332-kube-state-metrics-v2/
    kube-state-metrics-v2:
      gnetId: 13332
      revision: 12
      datasource: Prometheus
    # Ref: https://grafana.com/grafana/dashboards/12660-kubernetes-persistent-volumes/
    kubernetes-persistent-volumes:
      gnetId: 12660
      revision: 1
      datasource: Prometheus
    # Ref: https://grafana.com/grafana/dashboards/12006-kubernetes-apiserver/
    kubernetes-apiserver:
      gnetId: 12006
      revision: 1
      datasource: Prometheus
    # Ref: https://grafana.com/grafana/dashboards/315-kubernetes-cluster-monitoring-via-prometheus/
    kubernetes-cluster-monitoring:
      gnetId: 315
      revision: 3
      datasource: Prometheus

alerting: {}
notifiers: {}
dashboardsConfigMaps: {}
