##############################################################################################################
# General
##############################################################################################################

airflowVersion: 2.6.2

##############################################################################################################
# Dags
##############################################################################################################

executor: KubernetesExecutor
allowPodLaunching: true

dags:
  persistence:
    enabled: true
    size: 2Gi
    storageClassName: hd-hostpath
    existingClaim: airflow-local-dags-pvc
  gitSync:
    enabled: false  # Note: On a full gitops development flow, an enabled git sync should be a better approach

scheduler:
  replicas: 1

triggerer:
  enabled: true
  replicas: 1
  persistence:
    enabled: true
    size: 20Gi
    storageClassName: hd-hostpath
    fixPermissions: false

##############################################################################################################
# Databases
##############################################################################################################

data:
  metadataSecretName: airflow-metadata-secret  # pragma: allowlist secret

redis:
  enabled: true
  persistence:
    enabled: true
    size: 2Gi
    storageClassName: hd-hostpath
  passwordSecretName: airflow-redis-secret  # pragma: allowlist secret

postgresql:
  enabled: true
  image:
    tag: "11"
  auth:
    enablePostgresUser: true
    existingSecret: postgres-secrets  # pragma: allowlist secret
    username: airflow-user
    secretKeys:
      adminPasswordKey: postgres-password  # pragma: allowlist secret
      userPasswordKey: user-password  # pragma: allowlist secret
      replicationPasswordKey: replication-password  # pragma: allowlist secret

pgbouncer:
  enabled: false

##############################################################################################################
# Logs and Metrics
##############################################################################################################

logs:
  persistence:
    enabled: false
    size: 10Gi
    storageClassName: hd-hostpath

statsd:
  enabled: true

##############################################################################################################
# Webserver
##############################################################################################################

webserverSecretKeySecretName: airflow-webserver-secret  # pragma: allowlist secret

webserver:
  replicas: 1
  # Default user creation was changed to avoid secrets in the helm chart. To create an admin user it is
  # required to run the "users create" command inside the pod. See deployment documentation for details
  # about the procedure.
  defaultUser:
    enabled: false
  service:
    type: NodePort
    ports:
      - name: airflow-ui
        port: "{{ .Values.ports.airflowUI }}"
        nodePort: 30300

##############################################################################################################
# Networking
##############################################################################################################

ingress:
  web:
    enabled: false
  flower:
    enabled: false
networkPolicies:
  enabled: false

##############################################################################################################
# Security
##############################################################################################################

rbac:
  create: false
  createSCCRoleBinding: false

kerberos:
  enabled: false

##############################################################################################################
# Other
##############################################################################################################

migrateDatabaseJob:
  enabled: true
  ttlSecondsAfterFinished: 300
  useHelmHooks: true
  applyCustomEnv: true
