# Kafka Connect is an integration toolkit for streaming data between Kafka brokers and other systems using
# Connector plugins. Kafka Connect provides a framework for integrating Kafka with an external data source or
# target, such as a database, for import or export of data using connectors.
# (ref: https://strimzi.io/docs/operators/latest/overview)
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: kafka-connect-ingestion
  namespace: processing
  annotations:
    # Enables KafkaConnectors to create, delete, and reconfigure connectors
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.5.1
  replicas: 1
  bootstrapServers: kafka-ingestion-cluster-kafka-bootstrap:9092
  config:
    # These following values (group.id, offset.storage.topic, config.storage.topic, status.storage.topic)
    # should be unique for works for each Kafka Connect
    group.id: ingestion-cluster
    offset.storage.topic: ingestion-cluster-offsets
    config.storage.topic: ingestion-cluster-configs
    status.storage.topic: ingestion-cluster-status
    # Get configurations from Secrets, this is useful
    config.providers: secrets
    config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
  build:
    # This section creates the required docker image with the defined connector plugins and push this to a
    # private container registry. For new kind of connectors the plugins should be added here.
    output:
      type: docker
      image: 10.152.183.90:5000/kafka-connect-ingestion:latest
    plugins:
      # Ref: https://debezium.io/documentation/reference/stable/connectors/postgresql.html
      - name: debezium-postgres-source-connector
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/2.3.2.Final/debezium-connector-postgres-2.3.2.Final-plugin.tar.gz
      # Ref: https://docs.confluent.io/kafka-connectors/s3-sink/current/overview.html
      - name: confluent-s3-sink-connector
        artifacts:
          - type: zip
            url: https://d1i4a15mxbxib1.cloudfront.net/api/plugins/confluentinc/kafka-connect-s3/versions/10.5.4/confluentinc-kafka-connect-s3-10.5.4.zip
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kafka-connect-ingestion-read-secrets-role
  namespace: processing
rules:
  - apiGroups: [""]
    resources:
      - secrets
    resourceNames:
      - kafka-connect-postgres-user
      - kafka-connect-s3-user
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kafka-connect-ingestion-read-secrets-role-binding
  namespace: processing
subjects:
  - kind: ServiceAccount
    name: kafka-connect-ingestion-connect
    namespace: processing
roleRef:
  kind: Role
  name: kafka-connect-ingestion-read-secrets-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: user-domain-postgres-source-connector
  namespace: processing
  labels:
    strimzi.io/cluster: kafka-connect-ingestion
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    tasks.max: 1
    snapshot.mode: initial
    slot.name: userdomain
    topic.prefix: userdomain
    plugin.name: pgoutput
    database.dbname: user_domain
    database.hostname: postgresql.storage.svc.cluster.local
    database.port: 5432
    database.user: ${secrets:processing/kafka-connect-postgres-user:username} # pragma: allowlist secret
    database.password: ${secrets:processing/kafka-connect-postgres-user:password} # pragma: allowlist secret
    transforms: unwrap
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.drop.tombstones: "true"
    transforms.unwrap.delete.handling.mode: rewrite
    transforms.unwrap.add.fields.prefix: __debezium_
    transforms.unwrap.add.fields: name,op,db,table,source.ts_ms,txId,lsn,schema
    signal.enabled.channels: source
    signal.data.collection: public.debezium_signal
    table.exclude.list: public.debezium_signal
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: business-domain-postgres-source-connector
  namespace: processing
  labels:
    strimzi.io/cluster: kafka-connect-ingestion
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    tasks.max: 1
    snapshot.mode: initial
    slot.name: businessdomain
    topic.prefix: businessdomain
    plugin.name: pgoutput
    database.dbname: business_domain
    database.hostname: postgresql.storage.svc.cluster.local
    database.port: 5432
    database.user: ${secrets:processing/kafka-connect-postgres-user:username} # pragma: allowlist secret
    database.password: ${secrets:processing/kafka-connect-postgres-user:password} # pragma: allowlist secret
    transforms: unwrap
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.drop.tombstones: "true"
    transforms.unwrap.delete.handling.mode: rewrite
    transforms.unwrap.add.fields.prefix: __debezium_
    transforms.unwrap.add.fields: name,op,db,table,source.ts_ms,txId,lsn,schema
    signal.enabled.channels: source
    signal.data.collection: public.debezium_signal
    table.exclude.list: public.debezium_signal
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: checkin-domain-postgres-source-connector
  namespace: processing
  labels:
    strimzi.io/cluster: kafka-connect-ingestion
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    tasks.max: 1
    snapshot.mode: initial
    slot.name: checkindomain
    topic.prefix: checkindomain
    plugin.name: pgoutput
    database.dbname: checkin_domain
    database.hostname: postgresql.storage.svc.cluster.local
    database.port: 5432
    database.user: ${secrets:processing/kafka-connect-postgres-user:username} # pragma: allowlist secret
    database.password: ${secrets:processing/kafka-connect-postgres-user:password} # pragma: allowlist secret
    transforms: unwrap
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.drop.tombstones: "true"
    transforms.unwrap.delete.handling.mode: rewrite
    transforms.unwrap.add.fields.prefix: __debezium_
    transforms.unwrap.add.fields: name,op,db,table,source.ts_ms,txId,lsn,schema
    signal.enabled.channels: source
    signal.data.collection: public.debezium_signal
    table.exclude.list: public.debezium_signal
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: evaluations-domain-postgres-source-connector
  namespace: processing
  labels:
    strimzi.io/cluster: kafka-connect-ingestion
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    tasks.max: 1
    snapshot.mode: initial
    slot.name: evaluationsdomain
    topic.prefix: evaluationsdomain
    plugin.name: pgoutput
    database.dbname: evaluations_domain
    database.hostname: postgresql.storage.svc.cluster.local
    database.port: 5432
    database.user: ${secrets:processing/kafka-connect-postgres-user:username} # pragma: allowlist secret
    database.password: ${secrets:processing/kafka-connect-postgres-user:password} # pragma: allowlist secret
    transforms: unwrap
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.drop.tombstones: "true"
    transforms.unwrap.delete.handling.mode: rewrite
    transforms.unwrap.add.fields.prefix: __debezium_
    transforms.unwrap.add.fields: name,op,db,table,source.ts_ms,txId,lsn,schema
    signal.enabled.channels: source
    signal.data.collection: public.debezium_signal
    table.exclude.list: public.debezium_signal
